
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package rules;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHEET = 7;
  public static final int DIF = 5;
  public static final int SEMI = 8;
  public static final int INPUT = 9;
  public static final int EOF = 0;
  public static final int EQ = 4;
  public static final int EL = 10;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int LPAREN = 2;
  public static final int CHAINE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "EQ",
  "DIF",
  "CHAINE",
  "SHEET",
  "SEMI",
  "INPUT",
  "EL"
  };
}

